In [1]:
import numpy as np
import cv2
import sys
np.set_printoptions(threshold=sys.maxsize)

In [2]:
cap = cv2.VideoCapture('./train/trainGray.mp4')
frameCount = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
frameWidth = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frameHeight = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# buf = np.empty((frameCount, frameHeight, frameWidth), np.dtype('uint8'))
bufTemp = np.empty((frameCount, frameHeight * frameWidth), np.dtype('uint8'))

fc = 0
ret = True

# print(buf[fc].shape)
# print(np.array(cap.read())[1].shape)
# x = np.array(cap.read())[1]
# print(x[:,:,0].shape)

while (fc < frameCount  and ret):
#     ret, x = np.array(cap.read())
    ret, x = np.array(cap.read())
#     buf[fc] = x[:,:,0]
    x = x[:,:,0]
    x.shape = frameHeight*frameWidth
    bufTemp[fc] = x
    fc += 1

cap.release()

x = bufTemp[0, 0:frameHeight*frameWidth]
x.shape = (frameHeight, frameWidth)

In [23]:
y = np.loadtxt('./train/train.txt', np.dtype('float'))
theta = np.zeros(((frameHeight*frameWidth)+1), np.dtype('int16'))
m = frameHeight*frameWidth
lmbda = .01
alpha = .01
loopCount = 5
costArr = np.zeros(loopCount, np.dtype('float'))

In [24]:
for i in range(loopCount):
    cost = 0
    for j in range(1,frameCount):
        firstFrame = np.array(bufTemp[j-1], dtype='int16')
        secondFrame = np.array(bufTemp[j], dtype='int16')
        x = np.empty(((frameHeight*frameWidth)+1), np.dtype('int16'))
        x[0] = 1
        x[1:(frameHeight*frameWidth)+1] = secondFrame - firstFrame
        mean = np.mean(x)
        x = x - mean
        x = x/np.std(x)
#         grad = np.sum((np.dot(x, theta) - y[i])*x)/m
        grad = ((np.dot(x, theta) - y[j])*x)/m
        grad[1:len(grad)] = grad[1:len(grad)] + ((lmbda/m)*theta[1:len(theta)])
        cost = cost + ((np.dot(x, theta) - y[j])**2)/2
        theta = theta - (alpha*grad)
#     for j in range(1,frameCount):
#         firstFrame = np.array(bufTemp[j-1], dtype='int16')
#         secondFrame = np.array(bufTemp[j], dtype='int16')
#         x = np.empty(((frameHeight*frameWidth)+1), np.dtype('int16'))
#         x[0] = 1
#         x[1:(frameHeight*frameWidth)+1] = secondFrame - firstFrame
#         mean = np.mean(x)
#         x = x - mean
#         x = x/np.std(x)
#         cost = cost + (((np.dot(x, theta) - y[j])**2)/2)
    
    print(i)
    costArr[i] = cost/(2*m)
print(costArr)

0
1
2
3
4
[3.61257717 3.60492989 3.59946637 3.59518981 3.59163755]


In [10]:
a = np.array([1,5,10,15,16,20])
a = np.append(a, [4])
print(a[1:7])
# np.mean(a)

[ 5 10 15 16 20  4]


In [11]:
a = np.array([1,5,10,15,16,20])
b = np.array([1,2,3,4,5,6])
c = np.dot(a,b)
# print(np.dot(a,b))
d = np.array([1,2,3,4,5,6])
e = c * d
# print(c)
# print(e)
print(b*d)

[ 1  4  9 16 25 36]


In [12]:
120+80+60+30+10+1

301