In [3]:
import numpy as np
import cv2
import sys
np.set_printoptions(threshold=sys.maxsize)

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.copy(a)
print(a)
print(b)
a[2] = 11
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2 11  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [1]:
for i in range(100):
    if i % 3 == 0:
        print(i)

0
3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57
60
63
66
69
72
75
78
81
84
87
90
93
96
99
