In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import csv
import skvideo.io
from tqdm import tqdm
import cv2 as cv
%matplotlib inline
from scipy.optimize import rosen

In [ ]:
cap = cv.VideoCapture(cv.samples.findFile("../train/videos/trash/trainGray_Clipped.m4v"))
while(cap.isOpened()):
    ret, frame1 = cap.read()
    pic = cv.cvtColor(frame1,cv.COLOR_BGR2HSV)
    pic2 = np.copy(pic)
    pic3 = np.copy(pic)
    pic4 = np.copy(pic)
    pic5 = np.copy(pic)
    pic6 = np.copy(pic)
#     pic2[...,2] = pic2[...,2] * .2
    pic3[...,2] = pic3[...,2] * .7
    pic4[...,2] = pic4[...,2] * 1.2
    pic5[...,2] = pic5[...,2] * 1.4
#     pic6[...,2] = pic6[...,2] * 1.8

    pic = cv.cvtColor(pic,cv.COLOR_HSV2RGB)
#     pic2 = cv.cvtColor(pic2,cv.COLOR_HSV2RGB)
    pic3 = cv.cvtColor(pic3,cv.COLOR_HSV2RGB)
    pic4 = cv.cvtColor(pic4,cv.COLOR_HSV2RGB)
    pic5 = cv.cvtColor(pic5,cv.COLOR_HSV2RGB)
#     pic6 = cv.cvtColor(pic6,cv.COLOR_HSV2RGB)

    cv.imshow('frame1',pic)
#     cv.imshow('frame2',pic2)
    cv.imshow('frame3',pic3)
    cv.imshow('frame4',pic4)
    cv.imshow('frame5',pic5)
#     cv.imshow('frame6',pic6)
    if cv.waitKey(0) & 0xFF == ord('q'):
        break
cap.release()
cv.destroyAllWindows()

In [ ]:
cap = cv2.VideoCapture('./train/trainGray.mp4')

while(cap.isOpened()):
    ret, frame = cap.read()
    
    #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    #cv2.imshow('frame', gray)
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [ ]:
cap.release()
cv.destroyAllWindows()

In [ ]:
X = 0.1 * np.arange(10)
print(X)
print(rosen(X))
a = np.sum(100.0*(X[1:] - X[:-1]**2.0)**2.0 + (1 - X[:-1])**2.0)
print(a)
print(100.0*(X[1:] - X[:-1]**2.0)**2.0)

In [20]:
b = np.empty((0,2))
for i in range(10):
    print(i)
    rando = np.array([i, i+1])
    print(rando.shape)
    print(b.shape)
    b = np.append(b, [rando], axis=0)
print(b)
print(b[0])

0
(2,)
(0, 2)
1
(2,)
(1, 2)
2
(2,)
(2, 2)
3
(2,)
(3, 2)
4
(2,)
(4, 2)
5
(2,)
(5, 2)
6
(2,)
(6, 2)
7
(2,)
(7, 2)
8
(2,)
(8, 2)
9
(2,)
(9, 2)
[[ 0.  1.]
 [ 1.  2.]
 [ 2.  3.]
 [ 3.  4.]
 [ 4.  5.]
 [ 5.  6.]
 [ 6.  7.]
 [ 7.  8.]
 [ 8.  9.]
 [ 9. 10.]]
[0. 1.]


In [ ]:
b = None

In [9]:
c = np.arange(10, dtype='uint8')
print(c)
c = c - 5
print(c)
c.dtype='bool'
print(c)
print(c.shape, c.dtype)

[0 1 2 3 4 5 6 7 8 9]
[251 252 253 254 255   0   1   2   3   4]
[ True  True  True  True  True False  True  True  True  True]
(10,) bool


In [3]:
d = 3*180/np.pi/2
e = 3*(180/np.pi/2)
print(d)
print(e)

85.94366926962348
85.94366926962348


In [26]:
f = np.array([1,11,32,6,21,46,37,17])
print(np.mean(f))
l = ((np.sum(f[0:4])/4) + (np.sum(f[4:])/4))/2
print(l)

21.375
21.375


In [28]:
f = np.array([9,9,9,9,9,9])
print(np.mean(np.square(f)))

81.0


In [32]:
f = np.array([1,11,32,6,21,46,37,17])
g = np.array([[1,2],[1,2],[1,2],[1,2],[1,2],[1,2],[1,2],[1,2]])
print(g.shape, np.transpose(g).shape)
np.multiply(f,np.transpose(g))

(8, 2) (2, 8)


array([[ 1, 11, 32,  6, 21, 46, 37, 17],
       [ 2, 22, 64, 12, 42, 92, 74, 34]])