In [7]:
import numpy as np
import cv2
import sys
np.set_printoptions(threshold=sys.maxsize)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.copy(a)
print(a)
print(b)
a[2] = 11
print(a)
print(b)

In [ ]:
for i in range(10):
    if i % 3 == 0:
        print(i)
        i = i-2

In [14]:
cost = np.empty((3), np.dtype('float64'))
cost[0] = 1

In [2]:
cost = np.array([],np.dtype('float64'))

In [9]:
cost.shape

(3, 3)

In [10]:
print(cost)
print()
print(cost[:])
print()
print(cost[:,:])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
cost[0][0] = 1
print(cost)

In [11]:
cost[0] = np.append(cost[0], 2)
print(cost)

ValueError: could not broadcast input array from shape (4) into shape (3)

In [6]:
print(cost.dtype)
print(cost.shape)

float64
(3,)


In [ ]:
cost[2]

In [ ]:
if cost[0,0,2] > cost[0,0,2-1]